### ISSUE TITLE
Warning in 2.x+ Versions

### ISSUE THREAD

**Issue by danielrehmann** [tomorrow-one/transactional-outbox#234]
I encountered some warnings in our application after upgrading to the Spring Boot 3 supporting versions:

> Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: one.tomorrow.transactionaloutbox.reactive.repository.OutboxRepository

> Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: one.tomorrow.transactionaloutbox.reactive.model.OutboxRecord

It looks like that spring libraries that are not relying on spring boot need to set manually the compiler flag `-parameters` for their compilation to stop this warning from happening.

**Comment by magro** [comment]
Can we close this now, @danielrehmann ?

**Comment by danielrehmann** [comment]
I will check on Monday if the warnings are now gone 👍

**Comment by magro** [comment]
Ping @danielrehmann

**Comment by danielrehmann** [comment]
Warnings in our projects are gone now. I closed the issue. Thanks for the reminder @magro
