### ISSUE TITLE
Publish jobs failing

### ISSUE THREAD

**Issue by magro** [tomorrow-one/transactional-outbox#366]
After merging some PRs yesterday, all publish jobs failed with
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':commons:publishMavenPublicationToMavenRepository'.
> Failed to publish publication 'maven' to repository 'maven'
   > Could not PUT 'https://s01.oss.sonatype.org/content/repositories/snapshots/one/tomorrow/transactional-outbox/commons/2.3.3-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Content access is protected by token
```

See e.g. https://github.com/tomorrow-one/transactional-outbox/actions/runs/9628755950/job/26563307266

Did anything change here, @hnrkdmsk @danielrehmann?

**Comment by magro** [comment]
Sounds like a match: https://support.sonatype.com/hc/en-us/articles/360049469534-401-Content-access-is-protected-by-token-when-accessing-repositories

Unfortunately I don't have access to the related information for the sonatype tomorrow user.

**Comment by hnrkdmsk** [comment]
Hey @magro, sorry for the later response here. We've updated the login settings and now, everything is working again 🤗

**Comment by magro** [comment]
Perfect! 👍🙂
